// Única fuente de nombres de canal IPC. Preload expone esta lista; el renderer no inventa nombres.
export const IPC = {
  observerStatus: 'observer:status',
  observerSetEnabled: 'observer:set-enabled',
  observerTogglePause: 'observer:toggle-pause',
  bubbleToggle: 'bubble:toggle',
  windowMoveBy: 'window:move-by',
  windowDragEnd: 'window:drag-end',
  appQuit: 'app:quit',
  characterState: 'character:state',
  observerChanged: 'observer:changed',
  chatSend: 'chat:send',
  chatReply: 'chat:reply',
  chatThinking: 'chat:thinking',
  chatClear: 'chat:clear',
  memoryList: 'memory:list',
  memoryApprove: 'memory:approve',
  memoryReject: 'memory:reject',
  memoryDelete: 'memory:delete',
  memoryProposed: 'memory:proposed',
  memoryRefresh: 'memory:refresh',
  suggestionShow: 'suggestion:show',
  suggestionAccept: 'suggestion:accept',
  suggestionDismiss: 'suggestion:dismiss',
  fileEditList: 'file-edit:list',
  fileEditApprove: 'file-edit:approve',
  fileEditApproveAll: 'file-edit:approve-all',
  fileEditReject: 'file-edit:reject',
  fileEditRejectAll: 'file-edit:reject-all',
  fileEditProposed: 'file-edit:proposed',
  auditLog: 'audit:log',
  configGetFolders: 'config:get-folders',
  configAddFolder: 'config:add-folder',
  configRemoveFolder: 'config:remove-folder',
  usageGet: 'usage:get',
  modelsList: 'models:list',
  modelsSetActive: 'models:set-active',
  modelsSave: 'models:save',
  modelsDelete: 'models:delete',
  modelsDetect: 'models:detect',
  chatStop: 'chat:stop',
  chatHistory: 'chat:history',
  chatClearHistory: 'chat:clear-history',
  conversationsList: 'conversations:list',
  conversationNew: 'conversations:new',
  conversationOpen: 'conversations:open',
  conversationDelete: 'conversations:delete',
  conversationPin: 'conversations:pin',
  settingsGet: 'settings:get',
  settingsSet: 'settings:set',
  avatarChanged: 'avatar:changed',
} as const;

export const INVOKE_CHANNELS: string[] = [
  IPC.observerStatus, IPC.observerSetEnabled, IPC.observerTogglePause,
  IPC.chatSend, IPC.memoryList, IPC.memoryApprove, IPC.memoryReject, IPC.memoryDelete,
  IPC.suggestionAccept, IPC.suggestionDismiss,
  IPC.fileEditList, IPC.fileEditApprove, IPC.fileEditApproveAll, IPC.fileEditReject, IPC.fileEditRejectAll, IPC.auditLog,
  IPC.configGetFolders, IPC.configAddFolder, IPC.configRemoveFolder, IPC.usageGet,
  IPC.modelsList, IPC.modelsSetActive, IPC.modelsSave, IPC.modelsDelete, IPC.modelsDetect,
  IPC.settingsGet, IPC.settingsSet,
  IPC.chatStop, IPC.chatHistory, IPC.chatClearHistory,
  IPC.conversationsList, IPC.conversationNew, IPC.conversationOpen, IPC.conversationDelete, IPC.conversationPin,
];
export const SEND_CHANNELS: string[] = [IPC.bubbleToggle, IPC.windowMoveBy, IPC.windowDragEnd, IPC.appQuit];
export const LISTEN_CHANNELS: string[] = [IPC.characterState, IPC.observerChanged, IPC.chatReply, IPC.chatThinking, IPC.chatClear, IPC.memoryProposed, IPC.memoryRefresh, IPC.avatarChanged, IPC.suggestionShow, IPC.fileEditProposed];
